### PR TITLE
Add password command line argument

### PR DESCRIPTION
**Pull request by g0tmi1k**
Makes it even easier...

### CODE REVIEW

**Comment by firefart** [comment]
@g0tmi1k awesome thx for the change! I need to update the comment section again because the `-lcrypt` argument needs to be at the end but I will change it after merging.

**Comment by firefart** [comment]
PS: See https://github.com/FireFart/dirtycow/issues/1 for the lcrypt change

**Comment by g0tmi1k** [comment]
Ah! Sorry for making more work :P

**Comment by firefart** [comment]
np already changed :)

**Pull request merged**
